# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'boltic-ios-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'boltic-ios', :git => 'https://github.com/sagargen/boltic-ios.git', :tag => '0.0.1'

end
